---

# Available windows ec2 images.
win_ec2_default_images:
  'ap-southeast-2':
    - name: server-2016
      ami_id: ami-35832657

win_ec2_default_winrm_port: 5986
win_ec2_default_winrm_user: Administrator

win_ec2_default_security_group_rules:
  - proto: tcp
    from_port: 3389
    to_port: 3389
    cidr_ip: 0.0.0.0/0
  - proto: tcp
    from_port: 5986
    to_port: 5986
    cidr_ip: 0.0.0.0/0
