  - name: Install AD
    win_feature:
     name: AD-Domain-Services
     include_management_tools: yes
     include_sub_features: yes
  - name: Setup Active Directory Controller
    win_domain:
     dns_domain_name: "{{ ad_domain_name }}"
     safe_mode_password: "{{ ad_safe_mode_password }}"
    register: active_directory_controllers