- hosts: all
  name: This is a play within a playbook
  tasks:
   - name: install iis
     win_feature:
       name: Web-Server
       state: present

   - name: start iis service
     win_service:
       name: W3Svc
       state: started

   - name: Create website index.html
     win_copy:
       content: "Hello World"
       dest: C:\Inetpub\wwwroot\index.html