- hosts: mswin
  name: Install IIS on Windows
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  tasks:
   - name: install iis
     win_feature:
       name: Web-Server
       state: present

   - name: start iis service
     win_service:
       name: W3Svc
       state: started

   - name: Create website index.html
     win_copy:
       src: "AGL_Logo_Vertical_180px_RGB.png"
       dest: C:\Inetpub\wwwroot\AGL_Logo.png
       remote_src: yes
       
   - name: Template simple web site to iis_site_path as index.html
     win_template:
        src: 'index.html.j2'
        dest: C:\Inetpub\wwwroot\index.html
