- hosts: mswin
  name: Install IIS on Windows
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  tasks:
   - name: install iis
     win_feature:
       name: Web-Server
       state: present

   - name: start iis service
     win_service:
       name: W3Svc
       state: started

   - name: Create website index.html
     win_copy:
       content: "Hello World"
       dest: C:\Inetpub\wwwroot\index.html
       
