---
- hosts: windows
  vars: 
    ad_domain_name: ad1.e7ed.example.opentlc.com
    ad_safe_mode_password: jVMijRwLbI02gFCo2xkjlZ9lxEA7bm7zgg==
    ad_admin_user: "admin@{{ ad_domain_name}}"
    ad_admin_password: jVMijRwLbI02gFCo2xkjlZ9lxEA7bm7zgg==
  tasks:
  - name: Install AD
    win_feature:
     name: AD-Domain-Services
     include_management_tools: yes
     include_sub_features: yes

  - name: Setup Active Directory Controller
    win_domain:
     dns_domain_name: "{{ ad_domain_name }}"
     safe_mode_password: "{{ ad_safe_mode_password }}"
    register: active_directory_controllers
    
  - name: reboot once DC created
    win_reboot:
      reboot_timeout: 1200
    when: active_directory_controllers.reboot_required

  - name: List Domain Controllers
    win_shell: "nltest /dclist:{{ ad_domain_name }}"
    register: domain_list

  - debug:
     var: domain_list
     