---

language: python
python: '2.7'
env:
  global:
    - secure: TSyZUepSj1Bd+hqhKPrQKTkrmHiNNjySttRvNYXb2dkXLCqunSx0d3d0NBopcgba9V0S2gDGmOfW1mjiFwPmVhp0hoeQCyHFSUXBA7051ZgvYNoQmFPkcSi/y3TKXF9iBxbvbjJ0C26jGRMt5DsYhh0WSFPyIHdw+JbjcaMc/meFM3ddaTno8P5Sm0Li6fmnGyZDRGVMSzbMTYfZya0tQfg2ks0+1OXyhTVZKPo9AAcRTKAhzVMVRwO4VBBsjW10BUZLzH3is5MengmkyeMF0ov6HtNIN/MFKeHwng/sJc/4L7Ngn7HLdNNUkEIwjxvY6iepP6lt4oQSuY5aDh6uglODtonvuExy3pg6DAcv2ogG3sGPBSPvgZSiuqEERs+QVxDFxm1uy+DKjlWSAisfH6iV1GEJBShTHqLlzZUofgKc9w9W9wi0jAGdbJW5TyH5+kpIjLaqSBYZ4+O2S+iL4wpnx+XYhVjCWBMB+2+0gtaN/wGOMcwDnLsVe7qrqwxE2PGoSUsOhkO6B3ei/ldP82Vm/pKqHWR+kluEKLD6ggIaytC+Qyq0YVqp/CPifD7h6JqRSDUsr4IgCu+WSsjdFXfC70C3wqoRTnzfoLgD48rgoT1+i3rt2AlMWya3MssvsaPxSTGoJbdCsCORyXUsP1uzp+UDF7a7T73bYXXQe80=
    - secure: gGe4T0Xw3/o5KH+S1GQWKUb0paQbS7aLu4cHuZA+fczjYOvN1wuWcO4YJWvnAy65M1F8xLBwDcsscURGE86zp8omJG6QIK+XD0qLtiIa6FBIEnoo2al1gt6bLHUCpZarxoX6M/rng9pAmDGgBkIh3Zmgdq+Z7NMJnNSHwJLFDzPly2Dwj5rpib6ut5fGBzIAUXfnbZK+yMFuBTtNA68BzkFEnco6MU1KtG5OH01H7Lfh83Veb6fyhXjdanSguXzuoWp8JdsXR7N8vIHScjqsPg9V2rHQXs1VrQ4h7URn0pDwAjO36fxsH1h04IAMiMmHgtXKL1rG3kLPeDZSOzHFNgVKNK8YBQZDr8b5wKnNVMnATbkJcg1hWOfclXkhBG+Gp/ZxbxO85lyXOer7VXUuixAwTPAkoECVGIAsErBzBrDLhmwD9V5AanmqYK6BnUNdeW5dgicVWhIfL3xUW/eiqeHFsQ3kFswLS2Ea6nPP7a8dSwC70GybsEIELTqlDb8AAVdIiWlu3xsGzHEoKknYHFAgJlZ/YZPn5WgJsaeE8pOXThYmHsmNBae81LndAVZBI2aX/HswzjFI1ACIm4+xR8iCcLeXsmr300eogswcGe/ilwQUD1pO6S86lBXgXWx3h64eLdMWnEgMmHJRu5m1/ztoYV37eSK/aSAqPU3/tcs=
  matrix:
    - ANSIBLE_VERSION_SPEC="ansible>=2.0,<2.1"
    - ANSIBLE_VERSION_SPEC="ansible>=2.1,<2.2"
    - ANSIBLE_VERSION_SPEC="ansible>=2.2,<2.3"
    - ANSIBLE_VERSION_SPEC="ansible>=2.3,<2.4"

install:
  - pip install $ANSIBLE_VERSION_SPEC boto pywinrm
  - ansible --version

script:
  - ansible-playbook -i test/local -v -e "win_ec2_test_name=travis-win-ec2-$TRAVIS_JOB_NUMBER" test/main.yml

after_failure:
  - ansible-playbook -i test/local -t cleanup -v -e "win_ec2_test_name=travis-win-ec2-$TRAVIS_JOB_NUMBER" test/main.yml
