---

win_ec2_region: 'ap-southeast-2'
win_ec2_instance_type: 't2.medium'
win_ec2_security_group: 'win-ec2'
win_ec2_security_group_description: 'Security group for Ansible WinRM'
win_ec2_security_group_rules: '{{win_ec2_default_security_group_rules}}'
win_ec2_key_name: 'win_ec2'
win_ec2_public_key_path: '/var/lib/awx/venv/ansible/id_rsa.pub'
win_ec2_private_key_path: '/var/lib/awx/venv/ansible/id_rsa'
win_ec2_name_prefix: 'win-ec2'
win_ec2_images: '{{win_ec2_default_images[win_ec2_region]}}'
win_ec2_action: create
win_ec2_winrm_port: '{{win_ec2_default_winrm_port}}'
win_ec2_winrm_user: '{{win_ec2_default_winrm_user}}'
win_ec2_inventory_dest: '{{playbook_dir}}/inventory.win-ec2'
win_ec2_wait_for: true
win_ec2_wait_for_delay: 5
win_ec2_wait_for_timeout: 300
win_ec2_password_wait_timeout: 300