---

galaxy_info:
  author: Chris Church
  description: Create and destroy Windows instances on EC2.
  company: "Nine More Minutes, Inc."
  license: BSD
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions: ['all']
    - name: Fedora
      versions: ['all']
    - name: Ubuntu
      versions: ['all']
    - name: Debian
      versions: ['all']
  categories:
    - 'cloud:ec2'
dependencies: []
